### ISSUE TITLE
Хелп плз

### ISSUE THREAD

**Issue by x0rium** [Dzirrot/YaMusicDownloader#3]
`Downloading `Монгол Шуудан - Винни Пух`... done
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    download_playlist(liked_by_plist[0])
  File "main.py", line 26, in download_playlist
    print(f"Downloading `{track.artists[0]['name']} - {track.title}`", end="... ")`
Не подскажете где проблемка?

**Comment by x0rium** [comment]
`        if len(track.artists) < 1:
	        track.artists.append({'name':'noname'})
        print(f"Downloading `{track.artists[0]['name']} - {track.title}`", end="... ")
        if not track.available:`
решил все костылем )
